COLUMNS:
  Item_Identifier: string 
  Item_Weight: float64
  Item_Fat_Content: string
  Item_Visibility: float64
  Item_Type: string 
  Item_MRP: float64
  Outlet_Identifier: string 
  Outlet_Establishment_Year: int64  
  Outlet_Size: string 
  Outlet_Location_Type: string 
  Outlet_Type: string 

TARGET_COLUMN:
  Item_Outlet_Sales: float64